In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np
arr = np.array([1,2,3,4,5])

[1 2 3 4 5]


In [16]:
zeros_arr = np.zeros((3,3))
ones_arr = np.ones((2,2))
print (zeros_arr)
print (ones_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [19]:
arr = np.arange(10,100,5)
print (arr)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [48]:
lin_arr = np.linspace(10,100,5)
print (lin_arr)

[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


In [55]:
rand_arr = np.random.uniform(1,10,5)
np.round(rand_arr)

array([ 4.,  8.,  7.,  8., 10.])

In [60]:
arr = np.array([1,2,3,4,5],ndmin=32)
print (arr)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4 5]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]


In [72]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
element = arr[1,1]
slice_row = arr[1,:]
slice_column = arr[:,2]
mask = arr > 5
print(arr)
print(element)
print(slice_row)
print(slice_column)
print (mask)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
[4 5 6]
[3 6 9]
[[False False False]
 [False False  True]
 [ True  True  True]]


In [1]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [4]:
import pandas as pd

In [7]:
data = [10,20,30,40,50]
series_from_list = pd.Series(data)

In [13]:
import numpy as np
numpy_arr = np.array([1,2,3,4,5])
ser_numpy = pd.Series(numpy_arr)
print(ser_numpy)

0    1
1    2
2    3
3    4
4    5
dtype: int32


In [19]:
data = {'name': ['sam','jam','bam'],
        'age': [24,45,34],
        'gender': ['M','F','M']}
df_list = pd.DataFrame(data)
print(df_list)

  name  age gender
0  sam   24      M
1  jam   45      F
2  bam   34      M


In [23]:
data_lst = [['sam',34],['jam',45],['bam',64]]
df_lst = pd.DataFrame(data_lst,columns=['name','age'])
print(df_lst)

  name  age
0  sam   34
1  jam   45
2  bam   64


In [52]:
df_csv = pd.read_PIL(r'C:\NEUROBYTE\Data Scinece\Practice\POWER BI.jpg')

AttributeError: module 'pandas' has no attribute 'read_PIL'

In [43]:
print(df_csv)

    invoice_no  gender  age    category  quantity    price payment_method  \
0      I138884  Female   28    Clothing         5  1500.40    Credit Card   
1      I317333    Male   21       Shoes         3  1800.51     Debit Card   
2      I127801    Male   20    Clothing         1   300.08           Cash   
3      I173702  Female   66       Shoes         5  3000.85    Credit Card   
4      I337046  Female   53       Books         4    60.60           Cash   
..         ...     ...  ...         ...       ...      ...            ...   
195    I220863    Male   21       Books         4    60.60           Cash   
196    I530401  Female   32  Technology         2  2100.00           Cash   
197    I219555    Male   47    Clothing         3   900.24    Credit Card   
198    I316629  Female   41    Souvenir         3    35.19           Cash   
199    I795251    Male   33   Cosmetics         5   203.30           Cash   

    invoice_date     shopping_mall  Unnamed: 9 Unnamed: 10  Unnamed: 11  
0

In [47]:
df_csv.head(10)

invoice_no  gender  age   category  quantity    price payment_method  \
0    I138884  Female   28   Clothing         5  1500.40    Credit Card   
1    I317333    Male   21      Shoes         3  1800.51     Debit Card   
2    I127801    Male   20   Clothing         1   300.08           Cash   
3    I173702  Female   66      Shoes         5  3000.85    Credit Card   
4    I337046  Female   53      Books         4    60.60           Cash   
5    I227836  Female   28   Clothing         5  1500.40    Credit Card   
6    I121056  Female   49  Cosmetics         1    40.66           Cash   
7    I293112  Female   32   Clothing         2   600.16    Credit Card   
8    I293455    Male   69   Clothing         3   900.24    Credit Card   
9    I326945  Female   60   Clothing         2   600.16    Credit Card   

  invoice_date     shopping_mall  Unnamed: 9 Unnamed: 10  Unnamed: 11  
0   2022-08-05            Kanyon         NaN         SUM  3300.910000  
1   2021-12-12    Forum Istanbul         NaN       SUMIF  9302.560000  
2   2021-11-09         Metrocity         NaN         NaN  1011.960000  
3   2021-05-16      Metropol AVM         NaN       COUNT    28.000000  
4   2021-10-24            Kanyon         NaN     COUNTIF     4.000000  
5   2022-05-24    Forum Istanbul         NaN         NaN     4.000000  
6   2022-03-13      Istinye Park         NaN     AVERAGE   806.334211  
7   2021-01-13  Mall of Istanbul         NaN         NaN          NaN  
8   2021-11-04         Metrocity         NaN         NaN          NaN  
9   2021-08-22            Kanyon         NaN         NaN          NaN